





# 6.1 Inner function - function used inside a outer function
def outer_func(param):
    def inner_func(quote):
        return "String of: " + quote

    return inner_func(param)


print(outer_func('hi'))


# 6.2. Closures - a inner function that is dynamically generated by another function
# can change and remember the values of variables that were created outside the function
# we return a customized function
def outer_func_closure(param):
    def inner_func():
        return "String of: " + param

    # notice return val and input param, differs from above
    return inner_func


a = outer_func_closure('hello')
print(type(a))
print(a())




